---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart windrose
  ansible.builtin.command:
    cmd: ./windrose restart
    chdir: "{{ windrose_project_dir }}"
  become_user: "{{ windrose_user }}"
