---
kite_user: "kite"
kite_group: "kite"

kite_authorized_keys:
  - "{{ lookup('file', ansible_ssh_private_key_file + '.pub') }}"

kite_git_user_name: "Kite"
kite_git_user_email: "{{ lookup('env', 'KITE_EMAIL') | default('kite@localhost', true) }}"

kite_domain: "kite.cosmos.cboxlab.com"
kite_upstream_host: "127.0.0.1"
kite_upstream_port: 3000

kite_base_packages:
  - ca-certificates
  - curl
  - git
  - git-crypt
  - gnupg
  - jq
  - nginx
  - ripgrep
  - sudo
