---
- name: Restart Windrose Server
  hosts: windrose_servers
  become: true

  tasks:
    - name: Restart Windrose compose project
      community.docker.docker_compose_v2:
        project_src: "{{ windrose_project_dir }}"
        state: restarted
