---
- name: Stop Windrose Server
  hosts: windrose_servers
  become: true

  tasks:
    - name: Stop Windrose server with helper CLI
      ansible.builtin.command:
        cmd: ./windrose stop
        chdir: "{{ windrose_project_dir }}"
      become_user: "{{ windrose_user }}"
