---
- name: Update Windrose Server
  hosts: windrose_servers
  become: true

  tasks:
    - name: Update Windrose server with helper CLI
      ansible.builtin.command:
        cmd: ./windrose update
        chdir: "{{ windrose_project_dir }}"
      become_user: "{{ windrose_user }}"
