---
- name: Update Windrose Server
  hosts: windrose_servers
  become: true

  tasks:
    - name: Pull Windrose image
      community.docker.docker_compose_v2_pull:
        project_src: "{{ windrose_project_dir }}"

    - name: Recreate Windrose compose project
      community.docker.docker_compose_v2:
        project_src: "{{ windrose_project_dir }}"
        state: present
        recreate: always
