---
all:
  children:
    windrose_servers:
      hosts:
        windrose:
          ansible_host: windrose.cosmos.cboxlab.com
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
