---
valheim_server_name: "Valheim Speedrun"
valheim_world_name: "speedrun"
valheim_server_password: "{{ vault_valheim_server_password }}"
valheim_server_port: 2456
valheim_public: 0
valheim_crossplay: false
valheim_instance_id: ""
valheim_preset: ""
valheim_modifiers: []
valheim_mods_enabled: false
valheim_game_interface: "tailscale0"

tailscale_enabled: true
tailscale_accept_dns: false

valheim_admin_ids: []
valheim_permitted_list_enabled: false
valheim_permitted_ids: []

backup_enabled: true
backup_schedule: "hourly"
backup_retention:
  keep_last: 10
  keep_daily: 10
  keep_monthly: 12
backup_paths:
  - "{{ valheim_data_dir }}/worlds_local"
restic_repository: "s3:https://minio.cosmos.cboxlab.com/valheim-speedrun-backup"
