rebuild-fireland:
	nixos-rebuild switch --flake .#fireland --target-host root@192.168.1.70 --verbose

rebuild-chillyfries:
	nixos-rebuild switch --flake .#chillyfries --target-host root@192.168.1.76 --verbose

rebuild-valkyrie:
	nixos-rebuild switch --flake .#valkyrie --target-host root@192.168.1.79 --verbose

# rebuild-odin:
#   nixos-rebuild switch --flake .#odin --target-host root@192.168.1.75 --verbose
