---
- name: Create Valheim systemd service
  ansible.builtin.template:
    src: valheim.service.j2
    dest: /etc/systemd/system/valheim.service
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Ensure systemd is reloaded
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Valheim service
  ansible.builtin.systemd:
    name: valheim
    enabled: yes
    state: started

- name: Wait for Valheim server to start
  ansible.builtin.wait_for:
    port: "{{ valheim_server_port }}"
    delay: 15
    timeout: 120
  ignore_errors: yes

