rebuild:
	nixos-rebuild switch --flake .#titania --target-host root@192.168.1.40 --verbose
	nixos-rebuild switch --flake .#titania-worker1 --target-host root@192.168.1.78 --verbose
	# nixos-rebuild switch --flake .#titania-worker2 --target-host root@192.168.1.79 --verbose
